# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.public
        - ./.theme/content
  - touch:
      path: ./.theme/.env.local

  # Copy images to .public
  - copy:
      extension: .png
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .jpg
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .svg
      source: ./
      target: ./.theme/.public
  # Copy all files in public to .public
  - copy:
      source: ./.theme/public
      target: ./.theme/.public

  # # Extract diagrams
  # - extractDiagrams:
  #     source: ./
  #     target: ./.theme/.temp
  #     config:
  #       backgroundColor: '#092C2E'
  #       outputFormat: svg
  #       theme: base
  #       deviceScaleFactor: 1
  #       headless: new
  #       flowchart:
  #         useMaxWidth: false
  #       quadrantChart:
  #         xAxisPosition: 'bottom'
  #       themeVariables:
  #         primaryColor: '#FA465B'
  #         primaryTextColor: '#F7F7F7'
  #         primaryBorderColor': '#FA465B'
  #         lineColor: '#D5DBDB'
  #         secondaryColor: '#031819'
  #         secondaryTextColor: '#E9EBEB'
  #         secondaryBorderColor: '#031819'
  #         tertiaryColor: '#154245'
  #         activationBkgColor: '#FA465B'
  #         quadrant1Fill: '#255759'
  #         quadrant2Fill: '#154245'
  #         quadrant3Fill: '#092C2E'
  #         quadrant4Fill: '#154245'
  #         quadrantInternalBorderStrokeFill: '#031819'
  #         quadrantExternalBorderStrokeFill: '#031819'
  - copy:
      extension: .md
      source: ./
      target: ./.theme/content